### ISSUE TITLE
grid.auto_fit_columns not working

### ISSUE THREAD

**Issue by joseberlines** [bloomberg/ipydatagrid#302] opened 2022-03-03 22:07 UTC
I got the code from the example related to auto_fit_columns and I get the following:

![image](https://user-images.githubusercontent.com/33203439/156660642-6d5c73c9-b826-4f4a-8945-e276f133971a.png)

As you see the code is the same as in:
https://github.com/bloomberg/ipydatagrid/blob/main/examples/Column%20Width%20Auto-Fit.ipynb
but I changed just one line to make the words langer.

The result is that applying:
`grid.auto_fit_columns = True`

does not change anything and the content of the cells is cut as if nothing would have been changed.

Some idea what I am doing wrong?

THIS IS WHAT i WOULD HAE EXPECTED:
![image](https://user-images.githubusercontent.com/33203439/156661921-9c5eb822-8228-4a7a-a535-254ec001e277.png)

thanks

**Comment by ibdafna** [comment] 2022-03-11 05:39
Hello @joseberlines , I tested this functionality locally and it appears to be working fine. Can you check your installation, perhaps you're on an older version?

![auto_fit_columns](https://user-images.githubusercontent.com/24281433/157809061-7821a95b-16c9-4971-9c5d-18f3e8d7f23c.gif)

**Comment by ibdafna** [comment] 2022-03-16 04:46
@joseberlines can you check the browser console and let me know if you see any errors there?

**Comment by joseberlines** [comment] 2022-03-16 10:18
I will report soon. we have ipydatagrid in a JupyterHub environement and indeed the version currently is not the last one.

**Comment by joseberlines** [comment] 2022-03-17 12:35
Hi @ibdafna 
So version updated to 1.1.11 and this is the result:
![image](https://user-images.githubusercontent.com/33203439/158808525-e2c58758-f0d8-49be-b79a-9340d16d1e09.png)

code gist:
https://gist.github.com/joseberlines/694259ce8299e179cdc1877e6baaccbd

What I find strange:
a) the auto ajustment does not work fully. The table is created first small and when running:
g.auto_fit_columns = True
columns are getting more width but not entirely.

b) Since wraptext = True I would expect al least to go over several lines WITHIN a cell.

Putting info all together (and even if I am mixing up two things here)
1) I am looking for a way to auto adjust all the content of all the cells.
2) Ideally there should/could be a way to tell ipydatagrid: max width is 90px (or whatever) and from there wrap the text contained in a cell into new lines within the cell.

This would be pretty much like Excel and it would be a great enhancement.

**Comment by matangover** [comment] 2022-04-10 19:56
I can reproduce this easily by copying the code from the example notebook posted above, and adjusting the column contents to long values instead of the given short values. @ibdafna The GIF you showed shows resizing only by the column headers. The problem is when wanting to resize by the column contents. 

I'm using version 1.1.11 and I don't see any errors in the console. Thanks!

**Comment by matangover** [comment] 2022-04-10 19:58
Screenshot - 
I would expect "col1" to be resized based on the cell contents.

![image](https://user-images.githubusercontent.com/5028956/162637405-47da976b-1ca7-44fc-a109-a245b7f38158.png)

**Comment by matangover** [comment] 2022-04-10 20:05
(Perhaps this is simply a missing feature)

**Comment by ibdafna** [comment] 2022-04-13 19:01
@matangover Okay, yes, the auto sizing works only based on the columns, not the cells. I misunderstood the question. @joseberlines looking at your screenshot, you have the `text_wrap` feature set to true on the *header_renderer* `TextRenderer` object, which applies only to the column headers. You need to set this for the default renderer. You can use `default_renderer = <some_textrenderer_instance>` if you want to this apply to all cells. Or you can do this based on a column. I believe the documentation has a few examples. Thanks!

**Comment by vthemelis** [comment] 2023-01-26 23:48
@ibdafna, would it be possible to have some sort of option that will allow auto-adjusting the length of the columns based on the content rather than the column headers?

Effectively, I'm looking for what you get in Excel when double clicking the line that splits two adjacent rows in Excel.

At first, this can be provided through a programmatic API, but ideally, it would be great to auto-adjust the length by double clicking on the GUI.

**Comment by vthemelis** [comment] 2023-02-28 23:38
Added https://github.com/jupyterlab/lumino/pull/546 that implements the functionality described in this.

**Comment by vtgruk** [comment] 2023-08-17 12:10
https://github.com/jupyterlab/lumino/pull/546 is now released in JupyterLab https://github.com/jupyterlab/jupyterlab/releases/tag/v4.0.5 . I think we can now close this issue.

**Comment by martinRenou** [comment] 2023-09-06 11:33
Closing as it's now possible to double click on the column separators to auto-fit content, thanks a lot @vthemelis !

**Closed by martinRenou** 2023-09-06 11:33 UTC
