### ISSUE TITLE
How to create a sortable and filterable Datagrid

### ISSUE THREAD

**Issue by f3rn4nd0-c354r** [bloomberg/ipydatagrid#466] opened 2023-12-29 21:16 UTC
Hello,

I'm having a lot of troubles making this work. I can create a datagrid, but not sort it or filter it.

What ma I doing wrong?

```
import pandas as pd
from ipydatagrid import DataGrid

# Sample dictionary with words and frequencies
word_freq_dict = {'apple': 5, 'orange': 8, 'banana': 3, 'grape': 6}

# Convert the dictionary to a DataFrame
df = pd.DataFrame(word_freq_dict.items(), columns=['Word', 'Frequency'])

# Sort the DataFrame by the 'Frequency' column in descending order
df = df.sort_values(by='Frequency', ascending=False)

# Display the sorted DataFrame
dg = DataGrid(df)
dg
```

This creates a DataGrib, but one that is not sortable, and has no filters.

![image](https://github.com/bloomberg/ipydatagrid/assets/6833155/9fb9dc05-e2e8-47fc-adfb-1120174b404a)

Version:
Jupyter Labs Version 4.0.9

**Comment by afonit** [comment] 2024-01-23 14:17
When you click on the little funnels next to the column names - what happens?

Using your code, here is what happens for me:
![example_0011](https://github.com/bloomberg/ipydatagrid/assets/1798497/a7b5e242-d4f2-4bbc-bf43-94ce64bc5c53)

**Comment by f3rn4nd0-c354r** [comment] 2024-01-23 21:56
Nothing happens. The icon seems to be greyed out.
Is there some "browser log" I can check if there's some error?

**Comment by martinRenou** [comment] 2024-01-24 08:47
This is a duplicate of https://github.com/bloomberg/ipydatagrid/issues/446.

You need to either downgrade ipydatagrid or wait for 1.2.1 to be out. Sorry for the inconvenience.

**Closed** 2024-01-24 08:48 UTC
